apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: alertmanager-credentials
    creationPolicy: Owner

  data:
    - secretKey: slack-webhook-alerts
      remoteRef:
        key: mlops-platform/alertmanager/slack-webhook-alerts

    - secretKey: slack-webhook-critical
      remoteRef:
        key: mlops-platform/alertmanager/slack-webhook-critical