apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # The values file lives in our deploy repo
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.5.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/apps/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/srinivas-singireddy/mlops-platform-deploy.git
      targetRevision: main
      ref: values

    # Source 3: NEW — additional manifests (the ExternalSecret) for this workload
    - repoURL: https://github.com/srinivas-singireddy/mlops-platform-deploy.git
      targetRevision: main
      path: apps/kube-prometheus-stack
      directory:
        include: 'external-secret.yaml'      

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # NEW BLOCK — tells ArgoCD to ignore certain field differences
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.target.deletionPolicy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # Required for the large CRDs Prometheus uses
      - RespectIgnoreDifferences=true