apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 13.5.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/apps/loki/values.yaml
    - repoURL: https://github.com/srinivas-singireddy/mlops-platform-deploy.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: loki
    jsonPointers:
      - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
  
  
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true