apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: "1.8.6"
    helm:
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::897175693580:role/karpenter-controller-mlops-lab"

        extraVolumes:
          - name: aws-iam-token
            projected:
              defaultMode: 420
              sources:
                - serviceAccountToken:
                    audience: sts.amazonaws.com
                    expirationSeconds: 86400
                    path: token
        controller:
          extraVolumeMounts:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
        settings:
          clusterName: mlops-lab
          clusterEndpoint: "https://860BBF20F978107DBCA90D26EA44F8A3.gr7.eu-central-1.eks.amazonaws.com"
          interruptionQueue: "karpenter-mlops-lab"

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: karpenter.sh/nodepool
                      operator: DoesNotExist
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: karpenter
                topologyKey: kubernetes.io/hostname

        replicas: 2

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi

        tolerations: []

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true